path: /tmp/index

#writable: True
writable: False

embeddings:
  #path: sentence-transformers/all-MiniLM-L6-v2
  path: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2








